github: lbragile
ko_fi: lbragile
liberapay: lbragile
issuehunt: lbragile
custom:
  ["https://www.paypal.com/donate?hosted_button_id=4PRSE4BS72K2N&source=url", "https://www.buymeacoffee.com/lbragile"]
