export enum COLORS {
  DEFAULT_BACKGROUND = "#fff",

  DARK_BACKGROUND = "#1f1f1f",

  VALID_BACKGROUND = "#b4ff9a",
  INVALID_BACKGROUND = "#ff9a9a",
  VALID_SOLUTION = "#008000",
  INVALID_SOLUTION = "#f00",

  NAVBAR_BACKGROUND = "#eee",
  NAV_LINK_UNDERSCORE = "#8ac0ff",
  NAV_TEXT = "#000",

  SELECTED_TRANS_BACKGROUND = "#dfd",
  SELECTED_TRANS_BORDER = "#090",

  BLOCK_TRANS_BACKGROUND = "#c7e4ff",

  ROOT_CELL = "#4f9249",
  MIDDLE_CELLS = "#cf8b31",
  DATA_CELLS = "#7d95ff",
  PREVIEW_LINES = "#777"
}
