overwrite: true
schema: "http://localhost:4000/api/graphql"
documents: "src/graphql/**/*.gql"
generates:
  src/graphql/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
      - "fragment-matcher"
