name: Testing

on:
  push:
    branches: ["master", "develop", "test"]

jobs:
  unit:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'SKIP UNIT')"
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm i

      - name: Run Tests
        run: npm run test:unit

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage-final.json

  integration:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'SKIP INTEGRATION')"
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm i

      - name: Run Tests
        run: npm run test:integration

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage-final.json
